### ISSUE TITLE
where can I find ../DATA/BEAST_OUTPUT/skyride_Afrom2000.txt file, thanks.

### ISSUE THREAD

**Issue by liamxg** [maxbiostat/FMDV_AMERICA#124]
@maxbiostat

**Comment by maxbiostat** [comment]
Files have been uploaded. See if that solves your problem.

**Comment by liamxg** [comment]
@maxbiostat thanks.

**Comment by liamxg** [comment]
@maxbiostat is this paper published or not?

**Comment by maxbiostat** [comment]
Nope. On [ArXiv](http://arxiv.org/abs/1505.01105).

**Comment by liamxg** [comment]
thanks.

**Comment by liamxg** [comment]
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/46078579/204694935-199e5240-3d30-4521-a87b-40e4602f404b.png">

**Comment by liamxg** [comment]
could you please help me check this code, thanks.

**Comment by liamxg** [comment]
why there are two plots?

**Comment by liamxg** [comment]
@maxbiostat

**Comment by maxbiostat** [comment]
Closing as the original query seems to have been resolved and the later ones are unclear. Please feel free to open other issues with more focused questions.
