### ISSUE TITLE
Could you please help me out, thanks.

### ISSUE THREAD

**Issue by liamxg** [maxbiostat/FMDV_AMERICA#126]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/46078579/232039481-e6e0e176-da37-4cbe-802b-9f17e7912891.png">

**Comment by liamxg** [comment]
@maxbiostat

**Comment by liamxg** [comment]
in the "GLM_prepare_data.ipynb" file.

**Comment by maxbiostat** [comment]
See if [this](https://github.com/r-spatial/sf/issues/1762) helps.

**Comment by liamxg** [comment]
@maxbiostat thanks for your help on this issue. :)
